### ISSUE TITLE
Impressive result, how many pictures with fingure you take?

### ISSUE THREAD

**Issue by bailiqun** [tucan9389/FingertipEstimation-CoreML#1]
How many pictures in your dataset? 
could you open the dataset?

**Comment by tucan9389** [comment]
Thanks for interesting. In my case, used approximately 5k images. 
My dataset contains many personal life ☺️. If many peoples request, I’ll consider that.

**Comment by bluenucleus** [comment]
Wow, 5k is amazing! 
So badly want to try this but don't know how to train.

**Comment by bailiqun** [comment]
@tucan9389  thanks a lot ~

**Comment by tucan9389** [comment]
@escapy plz check [this repo](https://github.com/edvardHua/PoseEstimationForMobile) using TensorFlow if you want to train. 🙂I hope this will help you.
